name: vibel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_phoenix: ^1.1.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  hooked_bloc: ^1.4.3
  injecteo: ^1.0.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  injecteo_generator: ^1.0.1
  json_serializable: ^6.7.1
  linteo: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
